# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qt.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QLabel, QLineEdit, QListView, QMainWindow,
    QProgressBar, QPushButton, QScrollArea, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(724, 402)
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.mainTabWidget = QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName(u"mainTabWidget")
        self.mainTabWidget.setGeometry(QRect(0, 0, 721, 381))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTabWidget.sizePolicy().hasHeightForWidth())
        self.mainTabWidget.setSizePolicy(sizePolicy)
        self.mainTabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.mainTabWidget.setDocumentMode(False)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.pushButton_15 = QPushButton(self.tab_1)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(10, 300, 21, 41))
        self.listView_2 = QListView(self.tab_1)
        self.listView_2.setObjectName(u"listView_2")
        self.listView_2.setGeometry(QRect(10, 60, 261, 241))
        self.listView_2.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.comboBox_8 = QComboBox(self.tab_1)
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.comboBox_8.setGeometry(QRect(70, 20, 201, 31))
        self.label_3 = QLabel(self.tab_1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 20, 61, 31))
        self.launchBtn = QPushButton(self.tab_1)
        self.launchBtn.setObjectName(u"launchBtn")
        self.launchBtn.setGeometry(QRect(30, 300, 241, 41))
        self.mainTabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.listView = QListView(self.tab_2)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(90, 10, 241, 181))
        self.listView.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 78, 31))
        self.checkBox = QCheckBox(self.tab_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(340, 100, 141, 16))
        self.checkBox_2 = QCheckBox(self.tab_2)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(340, 40, 141, 16))
        self.checkBox_3 = QCheckBox(self.tab_2)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(340, 70, 141, 16))
        self.checkBox_4 = QCheckBox(self.tab_2)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QRect(340, 10, 141, 16))
        self.checkBox_4.setChecked(True)
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 200, 78, 21))
        self.lineEdit_7 = QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(90, 200, 241, 31))
        self.pushButton_3 = QPushButton(self.tab_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 310, 121, 31))
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 250, 71, 16))
        self.comboBox = QComboBox(self.tab_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(90, 241, 71, 31))
        self.comboBox_2 = QComboBox(self.tab_2)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(170, 241, 161, 31))
        self.progressBar = QProgressBar(self.tab_2)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(10, 280, 161, 23))
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)
        self.progressBar_2 = QProgressBar(self.tab_2)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(170, 280, 161, 23))
        self.progressBar_2.setValue(0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setInvertedAppearance(False)
        self.checkBox_5 = QCheckBox(self.tab_2)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(340, 130, 171, 16))
        self.checkBox_5.setChecked(True)
        self.mainTabWidget.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_12 = QLabel(self.tab_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 15, 111, 21))
        self.comboBox_5 = QComboBox(self.tab_5)
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(110, 10, 251, 31))
        self.pushButton_4 = QPushButton(self.tab_5)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(10, 110, 90, 31))
        self.pushButton_9 = QPushButton(self.tab_5)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(620, 10, 81, 31))
        self.lineEdit_5 = QLineEdit(self.tab_5)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(360, 10, 261, 31))
        self.pushButton_14 = QPushButton(self.tab_5)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(110, 110, 90, 31))
        self.scrollArea = QScrollArea(self.tab_5)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 150, 351, 201))
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 360, 818))
        self.label_15 = QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 390, 111, 21))
        self.listView_shaderpacks = QListView(self.scrollAreaWidgetContents)
        self.listView_shaderpacks.setObjectName(u"listView_shaderpacks")
        self.listView_shaderpacks.setGeometry(QRect(70, 580, 251, 141))
        self.listView_shaderpacks.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listView_shaderpacks.setIconSize(QSize(64, 64))
        self.label_13 = QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 10, 111, 21))
        self.pushButton_8 = QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(70, 730, 111, 31))
        self.pushButton_5 = QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(70, 160, 111, 31))
        self.listView_mods = QListView(self.scrollAreaWidgetContents)
        self.listView_mods.setObjectName(u"listView_mods")
        self.listView_mods.setGeometry(QRect(70, 390, 251, 141))
        self.listView_mods.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listView_mods.setIconSize(QSize(64, 64))
        self.label_14 = QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 200, 111, 21))
        self.listView_respacks = QListView(self.scrollAreaWidgetContents)
        self.listView_respacks.setObjectName(u"listView_respacks")
        self.listView_respacks.setGeometry(QRect(70, 200, 256, 141))
        self.listView_respacks.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listView_respacks.setIconSize(QSize(64, 64))
        self.listView_saves = QListView(self.scrollAreaWidgetContents)
        self.listView_saves.setObjectName(u"listView_saves")
        self.listView_saves.setGeometry(QRect(70, 10, 256, 141))
        self.listView_saves.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listView_saves.setIconSize(QSize(64, 64))
        self.pushButton_6 = QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(70, 350, 111, 31))
        self.pushButton_7 = QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(70, 540, 111, 31))
        self.label_16 = QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 580, 111, 21))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit_9 = QLineEdit(self.tab_5)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(470, 100, 171, 31))
        self.label_21 = QLabel(self.tab_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 60, 300, 31))
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(18)
        font1.setBold(True)
        self.label_21.setFont(font1)
        self.pushButton_16 = QPushButton(self.tab_5)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(640, 100, 61, 31))
        self.pushButton_17 = QPushButton(self.tab_5)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(570, 310, 131, 31))
        self.checkBox_6 = QCheckBox(self.tab_5)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(370, 100, 100, 31))
        self.label_23 = QLabel(self.tab_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(370, 60, 300, 31))
        self.label_23.setFont(font1)
        self.pushButton_20 = QPushButton(self.tab_5)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(210, 110, 90, 31))
        self.DownloadFixBtn = QPushButton(self.tab_5)
        self.DownloadFixBtn.setObjectName(u"DownloadFixBtn")
        self.DownloadFixBtn.setGeometry(QRect(620, 40, 81, 31))
        self.mainTabWidget.addTab(self.tab_5, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.listView_4 = QListView(self.tab)
        self.listView_4.setObjectName(u"listView_4")
        self.listView_4.setGeometry(QRect(10, 10, 691, 301))
        self.pushButton_2 = QPushButton(self.tab)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 310, 111, 31))
        self.pushButton_22 = QPushButton(self.tab)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(120, 310, 81, 31))
        self.create_account = QWidget(self.tab)
        self.create_account.setObjectName(u"create_account")
        self.create_account.setGeometry(QRect(0, 0, 711, 351))
        self.create_account.setAutoFillBackground(True)
        self.label_4 = QLabel(self.create_account)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 81, 31))
        self.comboBox_9 = QComboBox(self.create_account)
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.setObjectName(u"comboBox_9")
        self.comboBox_9.setGeometry(QRect(100, 20, 171, 31))
        self.offline = QWidget(self.create_account)
        self.offline.setObjectName(u"offline")
        self.offline.setGeometry(QRect(10, 60, 691, 201))
        self.label_18 = QLabel(self.offline)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 10, 81, 31))
        self.lineEdit_2 = QLineEdit(self.offline)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(90, 10, 171, 31))
        self.pushButton_23 = QPushButton(self.create_account)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(10, 300, 101, 41))
        self.microsoft = QWidget(self.create_account)
        self.microsoft.setObjectName(u"microsoft")
        self.microsoft.setGeometry(QRect(10, 60, 551, 201))
        self.microsoft.setAutoFillBackground(True)
        self.label_19 = QLabel(self.microsoft)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 10, 81, 31))
        self.pushButton_24 = QPushButton(self.microsoft)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(10, 10, 251, 31))
        self.pushButton_25 = QPushButton(self.create_account)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(110, 300, 101, 41))
        self.pushButton_26 = QPushButton(self.tab)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(200, 310, 81, 31))
        self.mainTabWidget.addTab(self.tab, "")
        self.listView_4.raise_()
        self.pushButton_2.raise_()
        self.pushButton_22.raise_()
        self.pushButton_26.raise_()
        self.create_account.raise_()
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.scrollArea_2 = QScrollArea(self.tab_3)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(0, 0, 711, 301))
        self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 692, 500))
        self.pushButton_12 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(340, 140, 120, 31))
        self.pushButton_13 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(400, 55, 61, 31))
        self.progressBar_3 = QProgressBar(self.scrollAreaWidgetContents_2)
        self.progressBar_3.setObjectName(u"progressBar_3")
        self.progressBar_3.setGeometry(QRect(110, 175, 351, 23))
        self.progressBar_3.setValue(0)
        self.label_11 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 210, 111, 21))
        self.lineEdit_8 = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(110, 205, 351, 31))
        self.lineEdit = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(110, 55, 291, 31))
        self.label = QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 60, 111, 21))
        self.pushButton_11 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(220, 140, 120, 31))
        self.pushButton_10 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(110, 140, 111, 31))
        self.label_22 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 10, 450, 31))
        self.label_22.setFont(font1)
        self.label_24 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 290, 450, 31))
        self.label_24.setFont(font1)
        self.lineEdit_10 = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(110, 330, 291, 31))
        self.label_5 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 335, 111, 21))
        self.label_20 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 415, 111, 21))
        self.lineEdit_11 = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(110, 410, 291, 31))
        self.label_25 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 370, 450, 31))
        self.label_25.setFont(font1)
        self.lineEdit_12 = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(110, 455, 291, 31))
        self.label_26 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 460, 111, 21))
        self.label_2 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 111, 31))
        self.comboBox_7 = QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.comboBox_7.setGeometry(QRect(110, 100, 271, 31))
        self.pushButton_21 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(380, 100, 41, 31))
        self.comboBox_4 = QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(110, 250, 161, 31))
        self.label_10 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 250, 54, 31))
        self.pushButton_27 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(420, 100, 41, 31))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.pushButton = QPushButton(self.tab_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(0, 310, 121, 31))
        self.mainTabWidget.addTab(self.tab_3, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.label_17 = QLabel(self.tab_6)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 10, 481, 361))
        self.label_17.setTextFormat(Qt.TextFormat.AutoText)
        self.label_17.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.mainTabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.label_27 = QLabel(self.tab_7)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 10, 121, 31))
        self.label_27.setFont(font1)
        self.label_28 = QLabel(self.tab_7)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 50, 54, 31))
        self.lineEdit_13 = QLineEdit(self.tab_7)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(100, 50, 241, 31))
        self.label_29 = QLabel(self.tab_7)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 90, 91, 31))
        self.comboBox_3 = QComboBox(self.tab_7)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(260, 90, 81, 31))
        self.comboBox_6 = QComboBox(self.tab_7)
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(100, 90, 161, 31))
        self.pushButton_18 = QPushButton(self.tab_7)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(10, 130, 101, 31))
        self.listView_3 = QListView(self.tab_7)
        self.listView_3.setObjectName(u"listView_3")
        self.listView_3.setGeometry(QRect(10, 170, 331, 171))
        self.listView_3.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.pushButton_19 = QPushButton(self.tab_7)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(240, 130, 101, 31))
        self.mainTabWidget.addTab(self.tab_7, "")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 0, 711, 381))
        self.label_6.setPixmap(QPixmap(u"assets/bg.png"))
        self.label_6.setScaledContents(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_6.raise_()
        self.mainTabWidget.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.mainTabWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Spectrum Launcher", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"\u25b4", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u767b\u5f55\u4e3a", None))
        self.launchBtn.setText(QCoreApplication.translate("MainWindow", u"LaunchButton", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"\u542f\u52a8", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u5217\u8868", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"BMCLAPI \u955c\u50cf\u6e90", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u5feb\u7167\u7248\u672c", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u8fdc\u53e4\u7248\u672c", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u53d1\u5e03\u7248\u672c", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u540d\u79f0", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u7ec4\u52a0\u8f7d\u5668", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u65e0", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Forge", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Fabric", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Neoforge", None))

        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"\u81ea\u52a8\u4e0b\u8f7d Fabric-API(mod)", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Minecraft \u5b9e\u4f8b", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u547d\u540d", None))
        self.lineEdit_5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u65b0\u540d\u79f0", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Mod", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u5b58\u6863", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u5149\u5f71", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u5b58\u6863", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u8d44\u6e90\u5305", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u8d44\u6e90\u5305", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664Mod", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u5149\u5f71\u5305", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u4f8b\u6587\u4ef6", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8be5\u7248\u672c\u8bbe\u7f6e", None))
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528\u7279\u5b9aJava", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u4f8b\u8bbe\u7f6e", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"\u5237\u65b0", None))
        self.DownloadFixBtn.setText(QCoreApplication.translate("MainWindow", u"\u8865\u5168\u6587\u4ef6", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u7248\u672c\u7ba1\u7406", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8d26\u6237", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u7528\u6237\u7c7b\u578b", None))
        self.comboBox_9.setItemText(0, QCoreApplication.translate("MainWindow", u"\u79bb\u7ebf", None))
        self.comboBox_9.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5fae\u8f6f\u8d26\u6237", None))

        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u7528\u6237\u540d(\u79bb\u7ebf)", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa", None))
        self.label_19.setText("")
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528\u6d4f\u89c8\u5668\u7ee7\u7eed", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"\u53d6\u6d88", None))
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u8d26\u6237", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u8d26\u6237", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d Java 21", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u56de\u9000 Java \u8def\u5f84", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8def\u5f84", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Minecraft \u6587\u4ef6\u5939", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d Java 17", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d Java 8", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u8bbe\u7f6e", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"\u4e2a\u6027\u5316", None))
        self.lineEdit_10.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u5c06\u663e\u793a\u4e8e\u4e3b\u83dc\u5355\u5de6\u4e0b\u89d2", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u542f\u52a8\u5668\u4fe1\u606f", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"JVM\u5b57\u7b26\u4e32", None))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u7559\u7a7a\u4f7f\u7528\u9ed8\u8ba4\u503c", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"\u9ad8\u7ea7\u8bbe\u7f6e", None))
        self.lineEdit_12.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u7559\u7a7a\u4f7f\u7528\u9ed8\u8ba4\u503c \u62fc\u63a5\u81f3\u542f\u52a8\u9879\u672b\u5c3e", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"\u6e38\u620f\u53c2\u6570", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u7684 Java", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"2048M", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"256M", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"512M", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("MainWindow", u"768M", None))
        self.comboBox_4.setItemText(4, QCoreApplication.translate("MainWindow", u"1024M", None))
        self.comboBox_4.setItemText(5, QCoreApplication.translate("MainWindow", u"1536M", None))
        self.comboBox_4.setItemText(6, QCoreApplication.translate("MainWindow", u"3G", None))
        self.comboBox_4.setItemText(7, QCoreApplication.translate("MainWindow", u"4G", None))
        self.comboBox_4.setItemText(8, QCoreApplication.translate("MainWindow", u"6G", None))
        self.comboBox_4.setItemText(9, QCoreApplication.translate("MainWindow", u"8G", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u5185\u5b58\u5206\u914d", None))
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8bbe\u7f6e", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Spectrum Launcher</span></p><p>Spectrum Launcher \u662f\u4e00\u4e2a\u8f7b\u91cf\u5316\uff0c\u5f00\u6e90\u7684 Minecraft \u542f\u52a8\u5668\uff0c\u57fa\u4e8e Python \u4e0ePySide6\u3002</p><p>\u517c\u5bb9Fabric, Forge\u7b49 Mod \u52a0\u8f7d\u5668\uff1bModrinth\u6a21\u7ec4\u4e0b\u8f7d\uff1b\u7b80\u5355\u7684\u5404\u7248\u672c\u6587\u4ef6\u7ba1\u7406\uff1b\u6b63\u7248\u767b\u5f55</p><p>Github: <a href=\"https://github.com/HPLAY-dev/spectrum-minecraft/launcher\"><span style=\" text-decoration: underline; color:#0000ff;\">HPLAY-dev/spectrum-minecraft/launcher</span></a></p><p>Bilibili: <a href=\"https://space.bilibili.com/3493108044007466\"><span style=\" text-decoration: underline; color:#0000ff;\">UID: 3493108044007466</span></a></p><p>\u5f00\u6e90\u534f\u8bae: GNU GPL</p></body></html>", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22 Mod", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"\u540d\u79f0", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Minecraft \u7248\u672c", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"fabric", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"forge", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", u"neoforge", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("MainWindow", u"quilt", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("MainWindow", u"liteloader", None))

        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"\u5b89\u88c5\u6b64Mod", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Modrinth", None))
        self.label_6.setText("")
    # retranslateUi

