# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qt.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QLabel, QLineEdit, QListView, QMainWindow,
    QProgressBar, QPushButton, QScrollArea, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(724, 402)
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.mainTabWidget = QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName(u"mainTabWidget")
        self.mainTabWidget.setGeometry(QRect(0, 0, 721, 381))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTabWidget.sizePolicy().hasHeightForWidth())
        self.mainTabWidget.setSizePolicy(sizePolicy)
        self.mainTabWidget.setTabPosition(QTabWidget.North)
        self.mainTabWidget.setDocumentMode(False)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.LaunchBtn = QPushButton(self.tab_1)
        self.LaunchBtn.setObjectName(u"LaunchBtn")
        self.LaunchBtn.setGeometry(QRect(510, 300, 171, 41))
        self.tabWidget = QTabWidget(self.tab_1)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 20, 211, 81))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_2 = QPushButton(self.tab)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QRect(10, 10, 181, 31))
        self.pushButton_2.setFlat(False)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.lineEdit_6 = QLineEdit(self.tab_4)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(70, 10, 113, 31))
        self.label_19 = QLabel(self.tab_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 10, 41, 31))
        self.tabWidget.addTab(self.tab_4, "")
        self.comboBox_4 = QComboBox(self.tab_1)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(70, 110, 161, 31))
        self.label_10 = QLabel(self.tab_1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 110, 54, 31))
        self.DownloadFixBtn = QPushButton(self.tab_1)
        self.DownloadFixBtn.setObjectName(u"DownloadFixBtn")
        self.DownloadFixBtn.setGeometry(QRect(380, 300, 121, 41))
        self.pushButton_15 = QPushButton(self.tab_1)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(680, 300, 21, 41))
        self.listView_2 = QListView(self.tab_1)
        self.listView_2.setObjectName(u"listView_2")
        self.listView_2.setGeometry(QRect(510, 90, 191, 201))
        self.listView_2.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.label_18 = QLabel(self.tab_1)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(260, 10, 231, 41))
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(18)
        font1.setBold(True)
        self.label_18.setFont(font1)
        icon = QIcon()
        iconThemeName = u"media-playback-start"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.mainTabWidget.addTab(self.tab_1, icon, "")
        self.label_18.raise_()
        self.tabWidget.raise_()
        self.comboBox_4.raise_()
        self.label_10.raise_()
        self.DownloadFixBtn.raise_()
        self.LaunchBtn.raise_()
        self.pushButton_15.raise_()
        self.listView_2.raise_()
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.listView = QListView(self.tab_2)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(90, 10, 241, 181))
        self.listView.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 54, 21))
        self.checkBox = QCheckBox(self.tab_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(340, 100, 141, 16))
        self.checkBox_2 = QCheckBox(self.tab_2)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(340, 40, 141, 16))
        self.checkBox_3 = QCheckBox(self.tab_2)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(340, 70, 141, 16))
        self.checkBox_4 = QCheckBox(self.tab_2)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QRect(340, 10, 141, 16))
        self.checkBox_4.setChecked(True)
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 200, 54, 21))
        self.lineEdit_7 = QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(90, 200, 241, 31))
        self.pushButton_3 = QPushButton(self.tab_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 310, 121, 31))
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 250, 71, 16))
        self.comboBox = QComboBox(self.tab_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(90, 241, 71, 31))
        self.comboBox_2 = QComboBox(self.tab_2)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(170, 241, 161, 31))
        self.progressBar = QProgressBar(self.tab_2)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(10, 280, 161, 23))
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)
        self.progressBar_2 = QProgressBar(self.tab_2)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(170, 280, 161, 23))
        self.progressBar_2.setValue(0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setInvertedAppearance(False)
        self.checkBox_5 = QCheckBox(self.tab_2)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(340, 130, 171, 16))
        self.checkBox_5.setChecked(True)
        icon1 = QIcon()
        iconThemeName = u"emblem-downloads"
        if QIcon.hasThemeIcon(iconThemeName):
            icon1 = QIcon.fromTheme(iconThemeName)
        else:
            icon1.addFile(u".", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.mainTabWidget.addTab(self.tab_2, icon1, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_12 = QLabel(self.tab_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 15, 111, 21))
        self.comboBox_5 = QComboBox(self.tab_5)
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(110, 10, 591, 31))
        self.pushButton_4 = QPushButton(self.tab_5)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(110, 70, 111, 31))
        self.pushButton_9 = QPushButton(self.tab_5)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(280, 110, 81, 31))
        self.lineEdit_5 = QLineEdit(self.tab_5)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(110, 110, 171, 31))
        self.pushButton_14 = QPushButton(self.tab_5)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(230, 70, 131, 31))
        self.scrollArea = QScrollArea(self.tab_5)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 150, 351, 201))
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, -584, 360, 818))
        self.label_15 = QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 390, 111, 21))
        self.listView_shaderpacks = QListView(self.scrollAreaWidgetContents)
        self.listView_shaderpacks.setObjectName(u"listView_shaderpacks")
        self.listView_shaderpacks.setGeometry(QRect(70, 580, 251, 141))
        self.listView_shaderpacks.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.listView_shaderpacks.setIconSize(QSize(64, 64))
        self.label_13 = QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 10, 111, 21))
        self.pushButton_8 = QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(70, 730, 111, 31))
        self.pushButton_5 = QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(70, 160, 111, 31))
        self.listView_mods = QListView(self.scrollAreaWidgetContents)
        self.listView_mods.setObjectName(u"listView_mods")
        self.listView_mods.setGeometry(QRect(70, 390, 251, 141))
        self.listView_mods.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.listView_mods.setIconSize(QSize(64, 64))
        self.label_14 = QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 200, 111, 21))
        self.listView_respacks = QListView(self.scrollAreaWidgetContents)
        self.listView_respacks.setObjectName(u"listView_respacks")
        self.listView_respacks.setGeometry(QRect(70, 200, 256, 141))
        self.listView_respacks.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.listView_respacks.setIconSize(QSize(64, 64))
        self.listView_saves = QListView(self.scrollAreaWidgetContents)
        self.listView_saves.setObjectName(u"listView_saves")
        self.listView_saves.setGeometry(QRect(70, 10, 256, 141))
        self.listView_saves.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.listView_saves.setIconSize(QSize(64, 64))
        self.pushButton_6 = QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(70, 350, 111, 31))
        self.pushButton_7 = QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(70, 540, 111, 31))
        self.label_16 = QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 580, 111, 21))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit_9 = QLineEdit(self.tab_5)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(450, 100, 191, 31))
        self.label_21 = QLabel(self.tab_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 80, 61, 16))
        self.pushButton_16 = QPushButton(self.tab_5)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(640, 100, 61, 31))
        self.pushButton_17 = QPushButton(self.tab_5)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(570, 310, 131, 31))
        self.label_22 = QLabel(self.tab_5)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(380, 75, 61, 21))
        self.checkBox_6 = QCheckBox(self.tab_5)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(370, 100, 71, 31))
        icon2 = QIcon()
        iconThemeName = u"system-file-manager"
        if QIcon.hasThemeIcon(iconThemeName):
            icon2 = QIcon.fromTheme(iconThemeName)
        else:
            icon2.addFile(u".", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.mainTabWidget.addTab(self.tab_5, icon2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.scrollArea_2 = QScrollArea(self.tab_3)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(0, 0, 711, 351))
        self.scrollArea_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 709, 332))
        self.pushButton_12 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(400, 130, 61, 31))
        self.pushButton_13 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(400, 10, 61, 31))
        self.label_4 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 135, 111, 21))
        self.label_2 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 55, 111, 21))
        self.lineEdit_4 = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(110, 130, 291, 31))
        self.progressBar_3 = QProgressBar(self.scrollAreaWidgetContents_2)
        self.progressBar_3.setObjectName(u"progressBar_3")
        self.progressBar_3.setGeometry(QRect(110, 170, 351, 23))
        self.progressBar_3.setValue(0)
        self.label_11 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 205, 111, 21))
        self.label_3 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 95, 111, 21))
        self.lineEdit_8 = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(110, 200, 351, 31))
        self.lineEdit = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(110, 10, 291, 31))
        self.label = QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 15, 111, 21))
        self.lineEdit_2 = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(110, 50, 291, 31))
        self.pushButton_11 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(400, 90, 61, 31))
        self.pushButton = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 240, 121, 31))
        self.pushButton_10 = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(400, 50, 61, 31))
        self.lineEdit_3 = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(110, 90, 291, 31))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        icon3 = QIcon()
        iconThemeName = u"utilities-system-monitor"
        if QIcon.hasThemeIcon(iconThemeName):
            icon3 = QIcon.fromTheme(iconThemeName)
        else:
            icon3.addFile(u".", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.mainTabWidget.addTab(self.tab_3, icon3, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.label_17 = QLabel(self.tab_6)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 10, 481, 361))
        self.label_17.setTextFormat(Qt.PlainText)
        self.label_17.setTextInteractionFlags(Qt.NoTextInteraction)
        icon4 = QIcon()
        iconThemeName = u"insert-image"
        if QIcon.hasThemeIcon(iconThemeName):
            icon4 = QIcon.fromTheme(iconThemeName)
        else:
            icon4.addFile(u".", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.mainTabWidget.addTab(self.tab_6, icon4, "")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 0, 711, 381))
        self.label_6.setPixmap(QPixmap(u"assets/bg.png"))
        self.label_6.setScaledContents(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_6.raise_()
        self.mainTabWidget.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.mainTabWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Spectrum Launcher", None))
        self.LaunchBtn.setText(QCoreApplication.translate("MainWindow", u"\u542f\u52a8", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528\u6d4f\u89c8\u5668\u8fdb\u884c\u4e0b\u4e00\u6b65\u64cd\u4f5c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u6b63\u7248\u767b\u5f55", None))
        self.lineEdit_6.setText(QCoreApplication.translate("MainWindow", u"alpha", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u540d\u79f0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u79bb\u7ebf\u767b\u5f55", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"2048M", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"256M", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"512M", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("MainWindow", u"768M", None))
        self.comboBox_4.setItemText(4, QCoreApplication.translate("MainWindow", u"1024M", None))
        self.comboBox_4.setItemText(5, QCoreApplication.translate("MainWindow", u"1536M", None))
        self.comboBox_4.setItemText(6, QCoreApplication.translate("MainWindow", u"3G", None))
        self.comboBox_4.setItemText(7, QCoreApplication.translate("MainWindow", u"4G", None))
        self.comboBox_4.setItemText(8, QCoreApplication.translate("MainWindow", u"6G", None))
        self.comboBox_4.setItemText(9, QCoreApplication.translate("MainWindow", u"8G", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u5185\u5b58\u5206\u914d", None))
        self.DownloadFixBtn.setText(QCoreApplication.translate("MainWindow", u"\u8865\u5168\u6587\u4ef6", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"\u25b4", None))
        self.label_18.setText("")
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"\u542f\u52a8", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u5217\u8868", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"BMCLAPI \u955c\u50cf\u6e90", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u5feb\u7167\u7248\u672c", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u8fdc\u53e4\u7248\u672c", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u53d1\u5e03\u7248\u672c", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u540d\u79f0", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u7ec4\u52a0\u8f7d\u5668", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u65e0", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Forge", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Fabric", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Neoforge", None))

        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"\u81ea\u52a8\u4e0b\u8f7d Fabric-API(mod)", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Minecraft \u7248\u672c", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u547d\u540d", None))
        self.lineEdit_5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u65b0\u540d\u79f0", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6\u5939", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Mod", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u5b58\u6863", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u5149\u5f71", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u5b58\u6863", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u8d44\u6e90\u5305", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u8d44\u6e90\u5305", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664Mod", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u5149\u5f71\u5305", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u6587\u4ef6", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8be5\u7248\u672c\u8bbe\u7f6e", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u8bbe\u7f6e", None))
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"\u5f3a\u5236Java", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u7248\u672c\u7ba1\u7406", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Java 21 \u8def\u5f84", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Java 8 \u8def\u5f84", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u56de\u9000 Java \u8def\u5f84", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Java 17 \u8def\u5f84", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8def\u5f84", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Minecraft \u6587\u4ef6\u5939", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8bbe\u7f6e", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u8f7d", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Spectrum Launcher</span></p><p>Spectrum Launcher \u662f\u4e00\u4e2a\u8f7b\u91cf\u5316\uff0c\u5f00\u6e90\u7684 Minecraft \u542f\u52a8\u5668\uff0c\u57fa\u4e8e Python \u4e0ePyQt5\u3002</p><p>\u517c\u5bb9Fabric, Forge\u7b49 Mod \u52a0\u8f7d\u5668\u3002\u5f53\u524d\u6b63\u5728\u5b8c\u5584 Mod \u52a0\u8f7d\u5668\u7684\u517c\u5bb9\u3002</p><p>Github: <a href=\"https://github.com/HPLAY-dev/spectrum-minecraft/launcher\"><span style=\" text-decoration: underline; color:#0000ff;\">HPLAY-dev/spectrum-minecraft/launcher</span></a></p><p>Bilibili: <a href=\"https://space.bilibili.com/3493108044007466\"><span style=\" text-decoration: underline; color:#0000ff;\">UID: 3493108044007466</span></a></p><p>\u5f00\u6e90\u534f\u8bae: GNU GPL v3.0</p></body></html>", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.label_6.setText("")
    # retranslateUi

