import l18n
from PySide6.QtCore import QCoreApplication


def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", l18n.string("ui")["windowTitle"], None))
    self.LaunchBtn.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["launchBtn"], None))
    self.pushButton_2.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["useBrowserNextStep"], None))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", l18n.string("ui")["officialLoginTab"], None))
    self.lineEdit_6.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["alpha"], None))
    self.label_19.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["name"], None))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", l18n.string("ui")["offlineLoginTab"], None))
    self.comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory2048M"], None))
    self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory256M"], None))
    self.comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory512M"], None))
    self.comboBox_4.setItemText(3, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory768M"], None))
    self.comboBox_4.setItemText(4, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory1024M"], None))
    self.comboBox_4.setItemText(5, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory1536M"], None))
    self.comboBox_4.setItemText(6, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory3G"], None))
    self.comboBox_4.setItemText(7, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory4G"], None))
    self.comboBox_4.setItemText(8, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory6G"], None))
    self.comboBox_4.setItemText(9, QCoreApplication.translate("MainWindow", l18n.string("ui")["memory8G"], None))

    self.label_10.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["memoryAllocation"], None))
    self.DownloadFixBtn.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["downloadFixFiles"], None))
    self.pushButton_15.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["upArrow"], None))
    self.label_18.setText("")
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", l18n.string("ui")["launchTab"], None))
    self.label_7.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["versionList"], None))
    self.checkBox.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["bmclapiMirror"], None))
    self.checkBox_2.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["showSnapshotVersions"], None))
    self.checkBox_3.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["showAncientVersions"], None))
    self.checkBox_4.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["showReleaseVersions"], None))
    self.label_8.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["versionName"], None))
    self.pushButton_3.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["download"], None))
    self.label_9.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["modLoader"], None))
    self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", l18n.string("ui")["none"], None))
    self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", l18n.string("ui")["forge"], None))
    self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", l18n.string("ui")["fabric"], None))
    self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", l18n.string("ui")["neoforge"], None))

    self.checkBox_5.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["autoDownloadFabricAPI"], None))
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", l18n.string("ui")["downloadTab"], None))
    self.label_12.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["minecraftVersion"], None))
    self.pushButton_4.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["delete"], None))
    self.pushButton_9.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["rename"], None))
    self.lineEdit_5.setPlaceholderText(QCoreApplication.translate("MainWindow", l18n.string("ui")["newName"], None))
    self.pushButton_14.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["open"], None))
    self.label_15.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["mod"], None))
    self.label_13.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["versionSaves"], None))
    self.pushButton_8.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["deleteShaders"], None))
    self.pushButton_5.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["deleteSaves"], None))
    self.label_14.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["resourcePacks"], None))
    self.pushButton_6.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["deleteResourcePacks"], None))
    self.pushButton_7.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["deleteMods"], None))
    self.label_16.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["shaderPacks"], None))
    self.label_21.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["versionFiles"], None))
    self.pushButton_16.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["ellipsis"], None))
    self.pushButton_17.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["saveVersionSettings"], None))
    self.checkBox_6.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["forceJava"], None))
    self.label_23.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["versionSettings"], None))
    self.pushButton_20.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["refresh"], None))
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", l18n.string("ui")["versionManagementTab"], None))
    self.pushButton_12.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["download"], None))
    self.pushButton_13.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["ellipsis"], None))
    self.label_4.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["java21Path"], None))
    self.label_2.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["java8Path"], None))
    self.label_11.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["fallbackJavaPath"], None))
    self.label_3.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["java17Path"], None))
    self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", l18n.string("ui")["path"], None))
    self.label.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["minecraftFolder"], None))
    self.pushButton_11.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["download"], None))
    self.pushButton_10.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["download"], None))
    self.label_22.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["basicSettings"], None))
    self.label_24.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["personalization"], None))
    self.lineEdit_10.setPlaceholderText(QCoreApplication.translate("MainWindow", l18n.string("ui")["displayInBottomLeft"], None))
    self.label_5.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["launcherInfo"], None))
    self.label_20.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["jvmArguments"], None))
    self.lineEdit_11.setText("")
    self.lineEdit_11.setPlaceholderText(QCoreApplication.translate("MainWindow", l18n.string("ui")["useDefaultIfEmpty"], None))
    self.label_25.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["advancedSettings"], None))
    self.lineEdit_12.setPlaceholderText(QCoreApplication.translate("MainWindow", l18n.string("ui")["appendToLaunchArgs"], None))
    self.label_26.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["gameArguments"], None))
    self.pushButton.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["saveSettings"], None))
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", l18n.string("ui")["settingsTab"], None))
    self.label_17.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["aboutText"], None))
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", l18n.string("ui")["aboutTab"], None))
    self.label_27.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["searchMod"], None))
    self.label_28.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["name"], None))
    self.label_29.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["minecraftVersion"], None))
    self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", l18n.string("ui")["fabric"], None))
    self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", l18n.string("ui")["forge"], None))
    self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", l18n.string("ui")["neoforge"], None))
    self.comboBox_3.setItemText(3, QCoreApplication.translate("MainWindow", l18n.string("ui")["quilt"], None))
    self.comboBox_3.setItemText(4, QCoreApplication.translate("MainWindow", l18n.string("ui")["liteloader"], None))

    self.pushButton_18.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["search"], None))
    self.pushButton_19.setText(QCoreApplication.translate("MainWindow", l18n.string("ui")["installThisMod"], None))
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", l18n.string("ui")["modrinthTab"], None))
    self.label_6.setText("")
# retranslateUi