load("@rules_rust//rust:defs.bzl", "rust_shared_library")
load("@crates//:defs.bzl", "aliases", "all_crate_deps")

package(default_visibility = ["//visibility:public"])

rust_shared_library(
    name = "spectrum_core_native",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_features = ["python"],
    edition = "2021",
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    deps = all_crate_deps(),
    rustc_flags = select({
        "@platforms//os:windows": ["-C", "link-arg=/EXPORT:PyInit__spectrum_core"],
        "//conditions:default": [],
    }),
)
